mfem: fix link order of externalpackages to be in dependency order.
This fixes errors of type:

/home/balay/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.4.0/openmpi-3.1.0-7ws4tgx4z3oru5g5skjrxs5sobpeiyef/bin/mpic++  -O3 -I.. -I/home/balay/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.4.0/hypre-develop-ugdmbezw77vmgaywb6bk7pimyftf2dbt/include -I/home/balay/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.4.0/superlu-dist-develop-eey6vhcsphdb5izmtlfeuroxh5nensim/include -I/home/balay/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.4.0/parmetis-4.0.3-bjnbcsft5vhszrp2jpqgy4wtngwdg3wx/include -I/home/balay/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.4.0/metis-5.1.0-b4rslugy4pbn45rloijfc5el4asqcp6v/include -I/home/balay/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.4.0/sundials-3.1.0-2a4yisy4zkxunwjdv2bishg4jpev7set/include -I/home/balay/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.4.0/petsc-develop-6i45uho7dbjjqtopck6cguay7s3lkmsq/include -I/home/balay/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.4.0/zlib-1.2.11-5nus6knzumx4ik2yl44jxtgtsl7d54xb/include ex11p.cpp -o ex11p -L.. -lmfem -Wl,-rpath,/home/balay/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.4.0/hypre-develop-ugdmbezw77vmgaywb6bk7pimyftf2dbt/lib -Wl,-rpath,/home/balay/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.4.0/openblas-0.2.20-poqkjoyksnotpnkyk5m2spklsuuinkqn/lib -L/home/balay/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.4.0/hypre-develop-ugdmbezw77vmgaywb6bk7pimyftf2dbt/lib -L/home/balay/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.4.0/openblas-0.2.20-poqkjoyksnotpnkyk5m2spklsuuinkqn/lib -lHYPRE -lopenblas -L/home/balay/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.4.0/superlu-dist-develop-eey6vhcsphdb5izmtlfeuroxh5nensim/lib -L/home/balay/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.4.0/parmetis-4.0.3-bjnbcsft5vhszrp2jpqgy4wtngwdg3wx/lib -lsuperlu_dist -lparmetis -Wl,-rpath,/home/balay/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.4.0/metis-5.1.0-b4rslugy4pbn45rloijfc5el4asqcp6v/lib -L/home/balay/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.4.0/metis-5.1.0-b4rslugy4pbn45rloijfc5el4asqcp6v/lib -lmetis -Wl,-rpath,/home/balay/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.4.0/sundials-3.1.0-2a4yisy4zkxunwjdv2bishg4jpev7set/lib -L/home/balay/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.4.0/sundials-3.1.0-2a4yisy4zkxunwjdv2bishg4jpev7set/lib -lsundials_arkode -lsundials_cvode -lsundials_nvecserial -lsundials_kinsol -lsundials_nvecparhyp -lsundials_nvecparallel -Wl,-rpath,/home/balay/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.4.0/petsc-develop-6i45uho7dbjjqtopck6cguay7s3lkmsq/lib -L/home/balay/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.4.0/petsc-develop-6i45uho7dbjjqtopck6cguay7s3lkmsq/lib -lpetsc -lrt -Wl,-rpath,/home/balay/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.4.0/zlib-1.2.11-5nus6knzumx4ik2yl44jxtgtsl7d54xb/lib -L/home/balay/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.4.0/zlib-1.2.11-5nus6knzumx4ik2yl44jxtgtsl7d54xb/lib -lz
/usr/bin/ld: /home/balay/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.4.0/hypre-develop-ugdmbezw77vmgaywb6bk7pimyftf2dbt/lib/libHYPRE.so: undefined reference to symbol 'dtrsm_'
/home/balay/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.4.0/openblas-0.2.20-poqkjoyksnotpnkyk5m2spklsuuinkqn/lib/libopenblas.so: error adding symbols: DSO missing from command line